src/Entity/Book.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\Repository\BookRepository;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\HttpFoundation\File\File;
use Doctrine\Common\Collections\ArrayCollection;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=BookRepository::class)
 * @Vich\Uploadable
 */
class Book
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $Description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     *@var string|null
     *@ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
    *@var File|null
    *@Assert\Image(mimeTypes="image/jpeg")
    *@Vich\UploadableField(mapping="book_images", fileNameProperty="image")
    */
    private $imageFile;

    /**
     * @ORM\Column(type="datetime")
     */
    private $release_date;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isAvailable;

    /**
     * @ORM\ManyToMany(targetEntity=Category::class, inversedBy="books")
     */
    private $category;

    /**
     * @ORM\ManyToOne(targetEntity=Author::class, inversedBy="books")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $createdAt;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isRequested;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $requestedAt;

    /**
     * @ORM\ManyToOne(targetEntity=Account::class, inversedBy="books")
     */
    private $account;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $maxRequestedAt;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $isConfirmRequestedBook;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $borrowedAt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $returnedAt;

    public function __construct()
    {
        $this->category = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getReleaseDate(): ?\DateTimeInterface
    {
        return $this->release_date;
    }

    public function setReleaseDate(\DateTimeInterface $release_date): self
    {
        $this->release_date = $release_date;

        return $this;
    }

    public function getIsAvailable(): ?bool
    {
        return $this->isAvailable;
    }

    public function setIsAvailable(bool $isAvailable): self
    {
        $this->isAvailable = $isAvailable;

        return $this;
    }

    /**
     * @return Collection|Category[]
     */
    public function getCategory(): Collection
    {
        return $this->category;
    }

    public function addCategory(Category $category): self
    {
        if (!$this->category->contains($category)) {
            $this->category[] = $category;
        }

        return $this;
    }

    public function removeCategory(Category $category): self
    {
        $this->category->removeElement($category);

        return $this;
    }

    public function getAuthor(): ?Author
    {
        return $this->author;
    }

    public function setAuthor(?Author $author): self
    {
        $this->author = $author;

        return $this;
    }
    
    /**
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $imageFile
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->createdAt = new \DateTime('now');
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getIsRequested(): ?bool
    {
        return $this->isRequested;
    }

    public function setIsRequested(bool $isRequested): self
    {
        $this->isRequested = $isRequested;

        return $this;
    }

    public function getRequestedAt(): ?\DateTimeInterface
    {
        return $this->requestedAt;
    }

    public function setRequestedAt(?\DateTimeInterface $requestedAt): self
    {
        $this->requestedAt = $requestedAt;

        return $this;
    }

    public function getAccount(): ?Account
    {
        return $this->account;
    }

    public function setAccount(?Account $account): self
    {
        $this->account = $account;

        return $this;
    }

    public function getMaxRequestedAt(): ?\DateTimeInterface
    {
        return $this->maxRequestedAt;
    }

    public function setMaxRequestedAt(?\DateTimeInterface $maxRequestedAt): self
    {
        $this->maxRequestedAt = $maxRequestedAt;

        return $this;
    }

    public function getIsConfirmRequestedBook(): ?bool
    {
        return $this->isConfirmRequestedBook;
    }

    public function setIsConfirmRequestedBook(?bool $isConfirmRequestedBook): self
    {
        $this->isConfirmRequestedBook = $isConfirmRequestedBook;

        return $this;
    }

    public function getBorrowedAt(): ?\DateTimeInterface
    {
        return $this->borrowedAt;
    }

    public function setBorrowedAt(?\DateTimeInterface $borrowedAt): self
    {
        $this->borrowedAt = $borrowedAt;

        return $this;
    }

    public function getReturnedAt(): ?\DateTimeInterface
    {
        return $this->returnedAt;
    }

    public function setReturnedAt(?\DateTimeInterface $returnedAt): self
    {
        $this->returnedAt = $returnedAt;

        return $this;
    }
}

src/Controller/LibraryController.php
<?php

namespace App\Controller;

use App\Entity\Book;
use App\Entity\SearchBook;
use App\Form\SearchBookFormType;
use App\Repository\BookRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;

class LibraryController extends AbstractController
{
    /**
     * @Route("/catalogue", name="library")
     */
    public function index(
        BookRepository $bookRepository,
        Request $request
    ): Response {
        $searchBook = new SearchBook();
        $searchBook->page = $request->get('page', 1);

        $form = $this->createForm(SearchBookFormType::class, $searchBook);

        $form->handleRequest($request);
        
        $books = $bookRepository->findSearch($searchBook);

        if ($request->get('ajax')) {
            return new JsonResponse([
                'content' => $this->renderView('library/_book.html.twig', ['books' => $books]),
                'sort' => $this->renderView('library/_sortable.html.twig', ['books' => $books]),
                'pagination' => $this->renderView('library/_pagination.html.twig', ['books' => $books])
            ]);
        }

        return $this->render('library/index.html.twig', [
            'books' => $books,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/catalogue/{slug}", name="book")
     */
    public function book(Book $book): Response
    {
        return $this->render('library/book.html.twig', [
            'book' => $book,
        ]);
    }
}

templates/library/_book.html.twig
{% for book in books %}
	{% include 'library/_card.html.twig' %}
{% endfor %}

templates/library/_card.html.twig
<div class="card mb-3">
	<div class="row g-0">
		{% if book.image %}
			<div class="col-md-4">
				<img src="{{ vich_uploader_asset(book, 'imageFile') | imagine_filter('thumbnails_books') }}" class="img-fluid rounded-start" alt="lorem picsum">
			</div>
		{% else %}
			<div class="col-md-4">
				<img src="{{ asset('/images/nocover.jpg') | imagine_filter('thumbnails_books') }}" class="img-fluid rounded-start" alt="lorem picsum">
			</div>
		{% endif %}
		<div class="col-md-8" style="position: relative;">
			<div class="card-body">
				<h3 class="card-title" style="text-transform: uppercase;">{{ book.title }}</h3>
				<h4 class="card-title">{{ book.author.lastname }}
					{{ book.author.firstname }}
				</h4>
				{% for category in book.category %}
					<h5>
						<span class="badge bg-secondary">{{ category.title }}</span>
					</h5>
				{% endfor %}
				<p class="card-text">
					{{ book.description }}
				</p>
				<p class="card-text">
					<small class="text-muted">Date de publication:
						{{ book.releaseDate|date("d/m/Y") }}
					</small>
				</p>
				{% if book.isAvailable == true %}
					<button type="button" class="btn btn-success" data-bs-toggle="button" autocomplete="off">
						<i class="fas fa-plus"></i>
						Disponible
					</button>
				{% else %}
					<button type="button" class="btn btn-danger" disabled data-bs-toggle="button" autocomplete="off">Indisponible</button>
				{% endif %}
			</div>
			<div style="position: absolute; bottom: 1rem; right: 2rem">
				<a class="btn btn-lg custom-btn text-right" href="{{ path('book', {'slug': book.slug}) }}">Voir plus</a>
			</div>
		</div>
	</div>
</div>

templates/library/_pagination.html.twig
{{ knp_pagination_render(books, 'base/_pagination.html.twig') }}

templates/library/_sortable.html.twig
{{ knp_pagination_sortable(books, 'ordre alphabétique de:', 'b.title') }}

templates/library/book.html.twig
{% extends 'base.html.twig' %}

{% block title %}Recherche | médiathèque La Chapelle-Curreaux
{% endblock %}

{% block body %}
	{% if is_granted('ROLE_ADMIN') or (is_granted('ROLE_USER') and app.user.account.isActive == true) %}
		<div class="library--main_container container">
			<div class="row bg-light">
                <div class="col-12 container fs-5">
                    <nav aria-label="breadcrumb">
						<ol class="breadcrumb">
							<li class="breadcrumb-item"><a href="{{ path('home') }}">Accueil</a></li>
							<li class="breadcrumb-item"><a href="{{ path('library') }}">Le Catalogue</a></li>
							<li class="breadcrumb-item active" aria-current="page">{{ book.title }}</li>
						</ol>
					</nav>
                </div>
            </div>
			<div class="row justify-content-end mt-4">  
                <div class="col-lg-3">
                    <a href="{{ path('library') }}" class="btn btn-lg custom-btn"><i class="fas fa-arrow-left"></i> Retour</a>
                </div>
            </div>
			<div class="row justify-content-center">
				<div class="col-sm-12 col-md-6 col-lg-8 custom-col-2 py-2">
					<div class="card mb-3">
						<div class="row g-0">
							{% if book.image %}
								<div class="col-md-4">
									<img src="{{ vich_uploader_asset(book, 'imageFile') | imagine_filter('books') }}" class="img-fluid rounded-start" alt="lorem picsum">
								</div>
							{% endif %}
							<div class="col-md-8" style="position: relative;">
								<div class="card-body" style="position: relative;">
									<h3 class="card-title" style="text-transform: uppercase;">{{ book.title }}</h3>
									<h4 class="card-title">{{ book.author.lastname }}
										{{ book.author.firstname }}</h4>
									{% for category in book.category %}
										<h5>
											<span class="badge bg-secondary">{{ category.title }}</span>
										</h5>
									{% endfor %}
									<p class="card-text">
										{{ book.description }}
									</p>
									<p class="card-text">
										<small class="text-muted">Date de publication:
											{{ book.releaseDate|date("d/m/Y") }}</small>
									</p>
									{% if book.isAvailable == true %}
										<h4>
											<span class="badge bg-success p-3">Disponible</span>
										</h4>
									{% else %}
										<h4>
											<span class="badge bg-danger p-3">Indisponible</span>
										</h4>
									{% endif %}
								</div>
								{% if book.isAvailable == false %}
								{% else %}
								<div style="position: absolute; bottom: 1rem; right: 2rem">
									<a href="{{ path('request_book',{id: book.id}) }}" class="btn btn-lg btn-primary">RESERVER</a>
								</div>
								{% endif %}
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	{% else %}
		<div class="container vh-100 d-flex flex-column justify-content-center text-center">
			<h3>Votre compte est en attente de validation</h3>
		</div>
	{% endif %}
{% endblock %}

templates/library/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Recherche | médiathèque La Chapelle-Curreaux{% endblock %}

{% block body %}
    {% if is_granted('ROLE_ADMIN') or (is_granted('ROLE_USER') and app.user.account.isActive == true) %}
        <div class="library--main_container container js-filter">
            <div class="row bg-light">
                <div class="col-12 container fs-5">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item">
                                <a href="{{ path('home') }}">Accueil</a>
                            </li>
                            <li class="breadcrumb-item active" aria-current="page">Le catalogue</li>
                        </ol>
                    </nav>
                </div>
            </div>
            {% for flashMessage in app.session.flashbag.get('success') %}
            <div class="row">
                <div class="col-8 container">
                    <p class="text-center w-responsive mx-auto mb-5 alert alert-success">{{ flashMessage }}</p>
                </div>
            </div>
            {% endfor %}
            {{ form_start(form, {attr: {class: 'js-filter-form'}}) }}
            <div class="row justify-content-center">
                <div class="col-sm-12 col-md-4 col-lg-3 custom-col-1">
                    <div class="row custom-row">
                        <div class="col-12">
                            <div class="col-title">
                                <p class="text-center">
                                    trier par
                                </p>
                            </div>
                            <div class="col-user_text d-flex flex-column px-2">
                                <p class="text-center js-filter-sort">
                                    {% include 'library/_sortable.html.twig' %}
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="row custom-row">
                        <div class="col-12">
                            <div class="col-title">
                                <p class="text-center">
                                    Filtrer
                                </p>
                            </div>
                            <div class="col-user_text d-flex flex-column px-2">  
                                <div class="row mt-4">
                                    <div class="col-12">
                                        <h4>Titre :</h4>
                                        {{ form_row(form.search) }}  
                                    </div>                                   
                                </div>
                                <div class="row mt-4">
                                    <div class="col-6">
                                        <h4>Genre :</h4>
                                        {{ form_row(form.categories) }}
                                    </div>
                                    <div class="col-6">
                                        <h4>Auteur :</h4>
                                        {{ form_row(form.authors) }}
                                    </div>
                                </div>
                                <div class="row mt-4">
                                    <div class="col-12">
                                    <h4>Année de publication</h4>
                                        {{ form_row(form.publishedAt) }}
                                    </div>
                                </div>   
                                <div class="row mt-4">
                                    <div class="col-12">
                                        <h4>Disponibilité</h4>
                                        {{ form_row(form.isAvailable) }}
                                    </div>
                                </div>
                                <div class="row mt-4">
                                    <div class="col-12">
                                        <button class="btn custom-btn  w-100" type="submit">RECHERCHE</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-sm-12 col-md-6 col-lg-8 custom-col-2 py-2 js-filter-content">
                    {% include 'library/_book.html.twig' %}
                </div>
            </div> 
            <div class="d-flex justify-content-center pagination-lg js-filter-pagination">
                {% include 'library/_pagination.html.twig' %}
            </div>
        {{ form_end(form) }}
        </div>
    {% else %}
        <div class="container vh-100 d-flex flex-column justify-content-center text-center">
            <h3>Votre compte est en attente de validation</h3>
        </div>
    {% endif %}
{% endblock %}